---
- name: Elastic Beats Installation
  hosts: LinuxServers
  become: true
  become_user: root
  roles:
    - elastic.beats
  vars:
    beats_version: 7.17.0
    beat: metricbeat
    beat_conf:
      metricbeat.modules:
        - system
        - kafka
      enabled: true
  # tasks:
  #   - name: Ansible copy file force
  #     copy:
  #       src: metricbeat.yml
  #       dest: /etc/metricbeat/metricbeat.yml
  #       force: yes

  #   - name: Remove unnecessary packages
  #     apt:
  #       autoremove: yes
  #       autoclean: yes

  #   - name: Debian - Ensure metricbeat is installed
  #     apt:
  #       name: metricbeat=7.16.3
  #       state: present
  #       update_cache: yes
  #       force: yes
