- name: Create Kafka topic
  hosts: all
  tasks:
    - name: Ensure community.general collection is installed
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.general
      become: true
      become_user: ansible
      register: install_collection_result
      changed_when: install_collection_result.rc != 0

    - name: Create Kafka topic
      community.general.kafka_topic:
        name: phani-metricbeat
        state: present
        partitions: 1
        replication_factor: 1
        config:
          - item: retention.ms
            value: 3600000
      register: topic_creation_result

    - name: Display topic creation result
      debug:
        var: topic_creation_result
