- name: Create Kafka topic
  hosts: all
  tasks:
    - name: Create Kafka topic
      kafka_topic:
        name: phani-metricbeat
        state: present
        partitions: 1
        replication_factor: 1
        config:
          - item: retention.ms
            value: 3600000
      register: topic_creation_result

    - name: Display topic creation result
      debug:
        var: topic_creation_result
